name: hydroharvest

services:
  backend:
    container_name: hydroharvest-backend-1
    restart: always
    ports:
      - 81:81
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
    depends_on:
      - database
    networks:
      - hydroharvest-network
    environment:
      - DATABASE_URL
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    
  database:
    container_name: hydroharvest-database-1
    image: postgres:latest
    shm_size: 128mb
    restart: always
    ports:
      - 5431:5431
    networks:
      - hydroharvest-network
    volumes:
      - hydroharvest-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
networks:
  hydroharvest-network:

volumes:
  hydroharvest-storage:
