name: hydroharvest pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-production:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Run containers on remote
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP_ADDRESS }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd ~
            if [ ! -d "hydroharvest" ]; then
              git clone https://github.com/SucksToBeAnik/hydroharvest.git
            fi
            cd hydroharvest
            git remote remove origin || true  # Ensure no conflicting origin exists
            git remote add origin https://github.com/SucksToBeAnik/hydroharvest.git
            git fetch origin
            git reset --hard origin/main  # Ensure the working directory matches the main branch
            git pull origin main
            export POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            export POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            export DATABASE_URL=${{ secrets.DATABASE_URL }}
            docker compose up -d --build
